### PR TITLE
Add support for "Last Will" messages

### PR DESCRIPTION
**Pull request by nicramage**
- Adds  optional support for "Last Will" messages.  The topic, message and retain flag may optionally be passed to new.
- Adds an additional "disconnect" method so that graceful disconnects can be performed, which suppresses the publishing of the "Last Will" message from the server.
- Updated the documentation to reflect the additions.

### CODE REVIEW

**Comment by Juerd** [comment]
Thank you for the pull request. I'd like to take your implementation but with a separate method called `last_will` for configuring the will, instead of the three extra arguments to the constructor.

**Comment by Juerd** [comment]
Note: API changed between your version and mine.

**Comment by nicramage** [comment]
Cool, that's actually a better change. Do you want me to do it?

**Comment by nicramage** [comment]
Ahh, I see you already made the changes on your repo. Thanks for incorporating my changes.

**Pull request merged**
